[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/the-toyota-kata/"
  to = "https://softwarekaizen.substack.com/p/the-toyota-way-14-principles-from"
  status = 301
  force = true
